---
title: "Untitled"
author: "Heather Kates"
date: "2024-02-22"
output: html_document
---

```{r,oldcode}
#Subset the transformed data only to those compounds in the reported data
#Bind negative and positive normalized peak intensity data together; remove metadata and metabolite name columns and rows PER REPORT this number 
#version update 2.1 the way the PCA is done is corrected
oldDATA <- t(rbind(
  Client_Data_Download[["Pos.normalized.data"]][num_of_metadata:nrow(Client_Data_Download[["Pos.normalized.data"]]),3:(num_samples+2)],
  Client_Data_Download[["Neg.normalized.data"]][num_of_metadata:nrow(Client_Data_Download[["Neg.normalized.data"]]),3:(num_samples+2)]))

#Convert to numeric
oldDATA <- matrix(as.numeric(oldDATA),    # Convert to numeric matrix
                  ncol = ncol(oldDATA))

#Calculate 2 principle components
oldprin_comp <- prcomp(oldDATA, rank. = 2)
#Extract the components
oldcomponents <- oldprin_comp[["x"]]
#Make them a df
oldcomponents <- data.frame(oldcomponents)
#Add the sample names and types
oldcomponents <- cbind(oldcomponents,
                       t(Client_Data_Download[["Pos.normalized.data"]][1:(num_of_metadata-1),3:(num_samples+2)]),
                       colnames(Client_Data_Download[["Pos.normalized.data"]][1:(num_of_metadata-1),3:(num_samples+2)])
)
colnames(oldcomponents) <- c("PC1","PC2",contrast_var,"Samples")
palette <- c("red","blue","black","green","purple","orange","lightblue","magenta","lightpink")

if(length(class_order)>0){
  oldcomponents[[contrast_var]] <- factor(oldcomponents[[contrast_var]], levels = class_order)
}
oldfig <- plot_ly(oldcomponents, x = ~PC1, y = ~PC2, color = ~oldcomponents[[contrast_var]], colors = palette[1:num_groups], type = 'scatter', mode = 'markers',hoverinfo = "text",hovertext = paste(oldcomponents[[contrast_var]],oldcomponents$Samples,sep="\n"), marker=list(sizeref=10, sizemode="area"))%>%
  layout(
    legend=list(title=list(text='color')),
    plot_bgcolor='#e5ecf6',
    xaxis = list(
      title = "0",
      zerolinecolor = "#ffff",
      zerolinewidth = 2,
      gridcolor='#ffff'),
    yaxis = list(
      title = "1",
      zerolinecolor = "#ffff",
      zerolinewidth = 2,
      gridcolor='#ffff'),title="PCA")
oldfig
```

```{r,newfig}
  #We want to remove the metadata row(s) and all non sample cols from Client_Data_Download
 PCA_DATA <- data.frame(cbind(
   colnames(Client_Data_Download[["Pos.normalized.data"]][-num_of_metadata,] %>% select(Client_Data_Download_out[["metadata"]]$Sample.name)), #Sample names
   
                       t(Client_Data_Download[["Pos.normalized.data"]][1:(num_of_metadata-1),(num_of_metadata+1):(num_samples+2)]),#Class variable
                             t(rbind(
  Client_Data_Download[["Pos.normalized.data"]][-c(1:(num_of_metadata-1)),] %>% select(Client_Data_Download_out[["metadata"]]$Sample.name),
  Client_Data_Download[["Neg.normalized.data"]][-c(1:(num_of_metadata-1)),] %>% select(Client_Data_Download_out[["metadata"]]$Sample.name)))))
 
#Convert numbers to numeric
PCA_DATA[-c(1:num_of_metadata)] <- lapply(PCA_DATA[-c(1:num_of_metadata)], function(col) {
  # Try to convert to numeric
  numeric_col <- suppressWarnings(as.numeric(col))
  
  # If there are no NAs after the conversion or the original column was all NAs
  if (!any(is.na(numeric_col)) || all(is.na(col))) {
    return(numeric_col)
  } else {
    return(col)
  }
})
# calculate principle components
pca_res <- prcomp(PCA_DATA[,-c(1:num_of_metadata)], center = TRUE, scale. = FALSE,rank. = 2) #The old version used the defaults
oldprin_comp <- prcomp(oldDATA, rank. = 2)

scores <- pca_res[["x"]]

colors <- RColorBrewer::brewer.pal(num_groups, "Set1")
# Function to plot ellipse for each target
plot_ellipse_function <- function(target) {
  target_data <- as.data.frame(scores[PCA_DATA[2] == target, 1:2])
  target_color <- colors[which(unique(PCA_DATA[[2]]) == target)]
  
  # Ellipse
  ellipse_coords <- car::dataEllipse(target_data$PC1, target_data$PC2, 
                                     levels = 0.68, # roughly corresponds to 1 std dev
                                     plot.points = FALSE, add = TRUE, draw = FALSE)
  
  fig <<- fig %>% 
    add_polygons(x = ellipse_coords[,1], y = ellipse_coords[,2],
                 line = list(color = target_color, dash = "dot"),
                 fillcolor = target_color, opacity = 0.3,
                 showlegend = F,
                 hoverinfo = "skip")  # this tells plotly not to show any hover information for the ellipses
}

# Function to plot points for each target
plot_points_function <- function(target) {
  target_data <- as.data.frame(scores[PCA_DATA[2] == target, 1:2])
  target_color <- colors[which(unique(PCA_DATA[[2]]) == target)]
  
  text_data <- as.character(rownames(target_data))
  PC1 <- as.numeric(target_data$PC1)
  PC2 <- as.numeric(target_data$PC2)

  # Scatter points
  fig <<- fig %>% 
    add_trace(data = target_data,
              x = ~PC1, y = ~PC2, 
              type = "scatter",
              mode = "markers",
              name = target,
              marker = list(color = target_color),
              text = ~text_data,
              hoverinfo = "text")  # this tells plotly to display the text when hovering
}

fig <- plot_ly()

# First loop: Plot all ellipses
invisible(lapply(unique(PCA_DATA[[2]]), plot_ellipse_function))

# Second loop: Plot all points
invisible(lapply(unique(PCA_DATA[[2]]), plot_points_function))

fig
```
